[package]
name = "wasm-workflow-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fp-bindgen = "1"

[dependencies.temporal-workflow-interface]
path = "../workflow-interface"
version = "0.1"
